---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-my-custom-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: quay.io/4n4nd/s2i-custom-notebook:latest
    importPolicy:
      scheduled: true
    name: "latest"
